//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrandAnalytics.TwitterSpyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TwitterSpyService.ITwitterSpyService")]
    public interface ITwitterSpyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterSpyService/SpyTopics", ReplyAction="http://tempuri.org/ITwitterSpyService/SpyTopicsResponse")]
        BrandAnalytics.TwitterSpyService.SpyTopicsResponse SpyTopics(BrandAnalytics.TwitterSpyService.SpyTopicsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterSpyService/SpyTopics", ReplyAction="http://tempuri.org/ITwitterSpyService/SpyTopicsResponse")]
        System.Threading.Tasks.Task<BrandAnalytics.TwitterSpyService.SpyTopicsResponse> SpyTopicsAsync(BrandAnalytics.TwitterSpyService.SpyTopicsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterSpyService/CancelSpyTopics", ReplyAction="http://tempuri.org/ITwitterSpyService/CancelSpyTopicsResponse")]
        BrandAnalytics.TwitterSpyService.CancelSpyTopicsResponse CancelSpyTopics(BrandAnalytics.TwitterSpyService.CancelSpyTopicsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITwitterSpyService/CancelSpyTopics", ReplyAction="http://tempuri.org/ITwitterSpyService/CancelSpyTopicsResponse")]
        System.Threading.Tasks.Task<BrandAnalytics.TwitterSpyService.CancelSpyTopicsResponse> CancelSpyTopicsAsync(BrandAnalytics.TwitterSpyService.CancelSpyTopicsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SpyTopics", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SpyTopicsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] topics;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.TimeSpan duration;
        
        public SpyTopicsRequest() {
        }
        
        public SpyTopicsRequest(int token, string[] topics, System.TimeSpan duration) {
            this.token = token;
            this.topics = topics;
            this.duration = duration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SpyTopicsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SpyTopicsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TwitterSpy.Models.ReportModel SpyTopicsResult;
        
        public SpyTopicsResponse() {
        }
        
        public SpyTopicsResponse(TwitterSpy.Models.ReportModel SpyTopicsResult) {
            this.SpyTopicsResult = SpyTopicsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelSpyTopics", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelSpyTopicsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int token;
        
        public CancelSpyTopicsRequest() {
        }
        
        public CancelSpyTopicsRequest(int token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelSpyTopicsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelSpyTopicsResponse {
        
        public CancelSpyTopicsResponse() {
        }
    }
}
